apiVersion: v1
kind: Service
metadata:
  name: gafar-service
spec:
  selector:
    app: hello-world
  ports:
  - port: 8000
    targetPort: 80
  type: NodePort

# kubectl apply -f service.yml
# kubectl get services
# minikube ip
# minikube service gafar-service
#kubectl port-forward service/gafar-service 7080:8000
#Your application is now available at http://localhost:7080/
