apiVersion: v1
kind: Service
metadata:
  name: gafar-service
spec:
  selector:
    app: hello-world
  ports:
  - port: 8000
    targetPort: 80
  type: NodePort

# kubectl apply -f service.yml
# minikube service hello-world-service